name: trackasia_gl
description: A Flutter plugin for integrating trackasia Maps inside a Flutter application on Android, iOS and web platforms.
version: 1.0.9
homepage: https://github.com/track-asia/trackasia-flutter-gl

dependencies:
  flutter:
    sdk: flutter
  trackasia_gl_platform_interface: 1.0.7
  # trackasia_gl_platform_interface: 
  #   path: ../trackasia_gl_platform_interface
  trackasia_gl_web: 1.0.1
  # trackasia_gl_web: 
  #   path: ../trackasia_gl_web
  

flutter:
  plugin:
    platforms:
      android:
        package: com.trackasia.android
        pluginClass: TrackasiaMapsPlugin
      ios:
        pluginClass: TrackasiaMapsPlugin
      web:
        default_package: trackasia_gl_web

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: ">=2.8.1"
